name:                BJ
version:             0.1.0.0
github:              "https://github.com/Koukyosyumei/haskell_blackjack"
license:             BSD3
author:              "Koukyosyumei"
maintainer:          "koukyosyumei@hotmail.com"
copyright:           "2020 Koukyosyumei"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/BJ#readme>

dependencies:
- base >= 4.7 && < 5
- random-shuffle

library:
  source-dirs: src

executables:
  BJ-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BJ

tests:
  BJ-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BJ
